trigger:
  branches:
    include:
    - master
  paths:
    include:
    - LetsEncrypt/LetsEncrypt.Dashboard.Web/*
    - LetsEncrypt/LetsEncrypt.Managers/*
    - LetsEncrypt/LetsEncrypt.DataAccess/*
    - LetsEncrypt/LetsEncrypt.Model/*
    - .pipeline/pipelines-web.yml

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Use .NET SDK (9.0)'
  inputs:
    packageType: sdk
    version: 9.0.203
    includePreviewVersions: true
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages
  inputs:
    command: 'restore'
    projects: | 
      **/LetsEncrypt.Dashboard.Web.csproj

- task: DotNetCoreCLI@2
  displayName: Build Solution
  inputs:
    command: 'build'
    projects: | 
      **/LetsEncrypt.Dashboard.Web.csproj

- script: |
    dotnet publish ./LetsEncrypt/LetsEncrypt.Dashboard.Web --configuration "Release" --output ./LetsEncrypt/LetsEncrypt.Dashboard.Web/bin/Release/publish

- script: |
    cd ./LetsEncrypt/LetsEncrypt.Dashboard.Web
    docker build -t djohnnie/letsencrypt-web .
    docker login -u '$(dockerId)' -p '$(dockerPwd)'
    docker push djohnnie/letsencrypt-web